### ISSUE TITLE
Downloading icons

### ISSUE THREAD

**Issue by yellowwoods12** [rosshettel/the-noun-project#12]
Hi, 
how can I download the icons in a directory using the API call or this wrapper?
All I can see is that they return a JS object which I am not sure how can be used  to download that collection.

**Comment by rosshettel** [comment]
Hi, the Noun Project API and this npm package will just return a property with the URL to the icon. You'll need to add the functionality yourself to save the image at that URL to a directory - you'll want something like this: https://stackoverflow.com/questions/11944932/how-to-download-a-file-with-node-js-without-using-third-party-libraries
