### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by KudMath** [rosshettel/the-noun-project#9]
I'm having trouble with CORS wich block my requests... Any Idea ?

```Failed to load https://api.thenounproject.com/collection/5/icons?limit=10: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. ```

**Comment by rosshettel** [comment]
The CORS header would be coming from the noun projects server, they may be have CORS blocking any requests outside their domain. Are you trying to use the module from the frontend?

**Comment by KudMath** [comment]
Yep. It was something like that. I ended up passing through our api.
